apiVersion: v1
kind: ConfigMap
metadata:
  name: configserver-env
  namespace: configserver
data:
  SPRING_PROFILES_ACTIVE: git,kubernetes
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://gitlab.com/dube2/application-configuration.git
  SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: release/dev
  SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS: app-config
  SPRING_CLOUD_KUBERNETES_CONFIGSERVER_CONFIG_MAP_NAMESPACES: default
  SPRING_CLOUD_KUBERNETES_CONFIGSERVER_SECRETS_NAMESPACES: default
