apiVersion: v1
kind: Service
metadata:
  name: spring-configserver
  namespace: configserver
spec:
  selector:
    app: spring-configserver
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
