apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/QuangThanhG13/eks-nemi-gitops.git"
    targetRevision: release/main  # hoặc "main" nếu muốn sử dụng nhánh chính
    path: argocd/apps
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
