namespace: argocd

service:
  name: argocd-server
  port: 80

ingress:
  enabled: true
  className: my-aws-ingress-class
  alb:
    groupName: my-shared-alb
    scheme: internet-facing
    certificateArn: arn:aws:acm:ap-southeast-1:992382687445:certificate/221e7931-4473-48b1-a566-d8a565a1f974
  hosts:
      -paths:
        - path: /argocd/*
          pathType: Prefix
          serviceName: argocd-server
          servicePort: 443

