namespace: argocd

service:
  name: argocd-server
  port: 80

ingress:
  enabled: true
  className: alb
  alb:
    scheme: internet-facing
    certificateArn: arn:aws:acm:ap-southeast-1:992382687445:certificate/221e7931-4473-48b1-a566-d8a565a1f974
  hosts:
    - host: test.example.com
      paths:
        - path: /
          pathType: Prefix
